[project]
name = "mmm-evsi-study"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jax[cuda13]>=0.11.1",
    "marimo>=0.24.0",
    "numpyro>=0.21.0",
    "nutpie>=0.16.11",
    "pymc-marketing>=1.1.0",
]

[tool.uv.sources]
pymc-marketing = { git = "https://github.com/PabloRoque/pymc-marketing.git", rev = "5743b31038f2dd9396aa08d98168afdbdb5d86ff" }

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
